<a href="https://colab.research.google.com/github/obulreddy-k/Practical_ML/blob/main/Building_Data_Pipelines_for_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#from __future__ import absolute_import, division, print_function, unicode_literals

from __future__ import absolute_import, division, print_function, unicode_literals
try:
  !pip install tf-nightly-2.0-preview
except Exception:
  pass
import tensorflow as tf
import pathlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
np.set_printoptions(precision = 4)

dataset = tf.data.Dataset.from_tensor_slices([8,3,0,8,2,1])
dataset
print(dataset)

for elem in dataset:
  print(elem.numpy())

ERROR: Could not find a version that satisfies the requirement tf-nightly-2.0-preview (from versions: none)
ERROR: No matching distribution found for tf-nightly-2.0-preview
<TensorSliceDataset shapes: (), types: tf.int32>
8
3
0
8
2
1


In [9]:
it = iter(dataset)
print(next(it).numpy())

8


In [10]:
print(dataset.reduce(0,lambda state, value: state + value).numpy())

22


In [11]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4,10]))
dataset1.element_spec


TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [12]:
dataset2 = tf.data.Dataset.from_tensor_slices((tf.random.uniform([4]),
                                               tf.random.uniform([4,100],maxval = 100, dtype = tf.int32)))
dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(100,), dtype=tf.int32, name=None))

In [13]:
dataset3 = tf.data.Dataset.zip((dataset1,dataset2))
dataset3.element_spec


(TensorSpec(shape=(10,), dtype=tf.float32, name=None),
 (TensorSpec(shape=(), dtype=tf.float32, name=None),
  TensorSpec(shape=(100,), dtype=tf.int32, name=None)))

In [16]:
#Dataset containing a sparse tensor
dataset4 = tf.data.Dataset.from_tensors(tf.SparseTensor(indices = [[0,0],[1,2]],values = [1,2],dense_shape=[3,4]))
dataset4.element_spec

SparseTensorSpec(TensorShape([3, 4]), tf.int32)

In [17]:
#Use value_type to see the type of value represented by the element spec
dataset4.element_spec.value_type

tensorflow.python.framework.sparse_tensor.SparseTensor

In [18]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4,10], minval =1,maxval=10,dtype=tf.int32))
dataset1
for z in dataset1:
  print(z.numpy())


[4 7 1 7 8 1 1 6 9 8]
[9 6 9 4 8 6 4 1 2 6]
[1 9 8 5 9 9 5 5 2 9]
[8 2 4 8 7 2 5 7 8 2]
