<a href="https://colab.research.google.com/github/obulreddy-k/Practical_ML/blob/main/Hello_World.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
from __future__ import absolute_import, division, print_function, unicode_literals

!pip install tensorflow==2.0.0-beta1

import tensorflow as tf



In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [2]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape = (28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')

])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [3]:
model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

NameError: ignored

In [13]:
#0D Tensor
import numpy as np

x = np.array(10)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)


10
()
0
int64


In [15]:
#1D Tesnor
x = np.array([4,2,5,9])

print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)

[4 2 5 9]
(4,)
1
int64


In [17]:
#2D Tensor
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
int64


In [18]:
#3D Tensors
x = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[1,2,3],
               [4,5,6],
               [7,8,9]]])

print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)
3
int64


In [19]:
from __future__ import absolute_import,division,print_function,unicode_literals
#Install TensorFlow
!pip install tensorflow==2.0.0-beta1
import tensorflow as tf

In [21]:
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()
print("No of axes in Tensor = %d"%x_train.ndim)
print("Shape of a tensor :", x_train.shape)
print("Data type  of a tensor element:",x_train.dtype)
print("No of axes in tensor = ",y_train.ndim)
print("Shape of a tensor:",y_train.shape)
print("Data type of tensor elements:",y_train.dtype)

11493376/11490434 [==============================] - 0s 0us/step
No of axes in Tensor = 3
Shape of a tensor : (60000, 28, 28)
Data type  of a tensor element: uint8
No of axes in tensor =  1
Shape of a tensor: (60000,)
Data type of tensor elements: uint8
No of axes in Tensor = 3
Shape of a tensor : (60000, 28, 28)
Data type  of a tensor element: uint8
No of axes in tensor =  1
Shape of a tensor: (60000,)
Data type of tensor elements: uint8
