<a href="https://colab.research.google.com/github/obulreddy-k/Practical_ML/blob/main/Mathematical_foundations_deepLearn_file2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
w = np.array([[1,0.5],[2,1]])
print("# of axes - w = %d"%w.ndim)
print("Shape of w = ",w.shape)
print(w)

# of axes - w = 2
Shape of w =  (2, 2)
[[1.  0.5]
 [2.  1. ]]


In [4]:
input = np.array([[1,2],[-1,2]])
print("axes of input : ", input.ndim)
print("Shape of input : ", input.shape)
print(input)

axes of input :  2
Shape of input :  (2, 2)
[[ 1  2]
 [-1  2]]


In [5]:
b = np.array([-2.0,0.5])
print("axes of b :", b.ndim)
print("Shape of b : ",b.shape)
print(b)


axes of b : 1
Shape of b :  (2,)
[-2.   0.5]


In [8]:
#Lets apply linear combination
z =  np.dot(w,input) + b
print(w.shape)
print(input.shape)
print(b.shape)
print(z.shape)
print(z)
d = np.dot(w,input)
print(d)

(2, 2)
(2, 2)
(2,)
(2, 2)
[[-1.5  3.5]
 [-1.   6.5]]
[[0.5 3. ]
 [1.  6. ]]
